### ISSUE TITLE
React の動画を見終わる

### ISSUE THREAD

**Issue by ltoppyl** [hacku-2022-kari/gamename-front-end#6]
## ✨ 概要
- React の動画を見終わる

## 🔥 ゴール

- React の動画を見終わって、実際にコードをかけるようにする

## 📄 参考資料

- xxx

## ✅ タスク

- [ ] xxx

**Comment by KEiJey** [comment]
新・日本一わかりやすいReact全部見て、
あと公式のチュートリアル終わったなり！

**Comment by ltoppyl** [comment]
公式のチュートリアルってこれ？？ https://ja.reactjs.org/tutorial/tutorial.html

**Comment by KEiJey** [comment]
そうそう。三目並べ

**Comment by ltoppyl** [comment]
激アツ🔥🔥！！
この Issue close してしまっていいよ！

**Comment by KEiJey** [comment]
close ボタンが迷子
何処や？

**Comment by ltoppyl** [comment]
一番下に 「Close Issue」っていうボタンあるよー

**Comment by KEiJey** [comment]
パッと探した感じ見つかんないかも
このイシュー、俺クローズできない説ない？
